version = 6

[[platforms]]
name = "kiro"
binary = "kiro-cli"

[[platforms]]
name = "opencode"
binary = "opencode"

[[platforms]]
name = "copilot"
binary = "copilot"

[[platforms]]
name = "gemini"
binary = "gemini"

[[platforms]]
name = "claude"
binary = "claude"

[[platforms]]
name = "codex"
binary = "codex"

[[platforms]]
name = "mistral"
binary = "vibe"

[[platforms]]
name = "blackbox"
binary = "blackbox"

[[platforms]]
name = "cursor"
binary = "agent"

[[platforms]]
name = "kilo"
binary = "kilo"

[[platforms]]
name = "cline"
binary = "cline"

[[platforms]]
name = "qwen"
binary = "qwen"

[[platforms]]
name = "continue"
binary = "cn"

[[platforms]]
name = "antigravity"
binary = "agy"

[[platforms]]
name = "mimocode"
binary = "mimo"
